import { Schema } from "mongoose";
import goalsScoredSchema from "./gameResultSubSchemas/allGoalsScored";
import penaltiesTakenSchema from "./gameResultSubSchemas/allPenalties";
import GoalieGameStatsSchema from "./gameResultSubSchemas/goalieGameStats";
import PlayerGameStatsSchema from "./gameResultSubSchemas/playerGameStats";

const GameResultSchema = new Schema(
  {
    otherGameStats: {
      league: String,
      seasonNumber: String,
      gameType: String,
      overtimeRequired: Boolean,
      overtimeLossTeam: String,
      homeTeam: String,
      awayTeam: String,
      homeTeamPoints: String,
      awayTeamPoints: String,
      winningTeam: String,
      losingTeam: String,
      faceOffs: String,
      ["GAME LENGTH"]: String,
      uniqueGameId: String,
    },
    allGoalsScored: [goalsScoredSchema],
    allPenalties: [penaltiesTakenSchema],
    awayTeamGameStats: {
      ["Away1ST GOALS"]: String,
      ["Away1ST SHOTS"]: String,
      ["Away1X ATT"]: String,
      ["Away1X GOALS"]: String,
      ["Away2ND GOALS"]: String,
      ["Away2ND SHOTS"]: String,
      ["Away3RD GOALS"]: String,
      ["Away3RD SHOTS"]: String,
      AwayATTACK: String,
      AwayBREAKAWAY: String,
      ["AwayBREAKAWAY GOALS"]: String,
      AwayCHECKS: String,
      ["AwayFACEOFFS WON"]: String,
      AwayGOALS: String,
      ["AwayOT GOALS"]: String,
      ["AwayOT SHOTS"]: String,
      ["AwayPASS ATT"]: String,
      ["AwayPASS COMP"]: String,
      AwayPENALTIES: String,
      ["AwayPENALTY SHOT GOALS"]: String,
      ["AwayPENALTY SHOTS"]: String,
      AwayPIM: String,
      ["AwayPP GOALS"]: String,
      ["AwayPP MIN"]: String,
      ["AwayPP OPP"]: String,
      ["AwayPP SHOTS"]: String,
      AwaySHG: String,
      AwaySHOTS: String,
      AwayTeam: String,
    },
    homeTeamGameStats: {
      ["Home1ST SHOTS"]: String,
      ["Home1ST GOALS"]: String,
      ["Home1X ATT"]: String,
      ["Home1X GOALS"]: String,
      ["Home2ND GOALS"]: String,
      ["Home2ND SHOTS"]: String,
      ["Home3RD GOALS"]: String,
      ["Home3RD SHOTS"]: String,
      HomeATTACK: String,
      HomeBREAKAWAY: String,
      ["HomeBREAKAWAY GOALS"]: String,
      HomeCHECKS: String,
      ["HomeFACEOFFS WON"]: String,
      HomeGOALS: String,
      ["HomeOT GOALS"]: String,
      ["HomeOT SHOTS"]: String,
      ["HomePASS ATT"]: String,
      ["HomePASS COMP"]: String,
      HomePENALTIES: String,
      ["HomePENALTY SHOT GOALS"]: String,
      ["HomePENALTY SHOTS"]: String,
      HomePIM: String,
      ["HomePP GOALS"]: String,
      ["HomePP MIN"]: String,
      ["HomePP OPP"]: String,
      ["HomePP SHOTS"]: String,
      HomeSHG: String,
      HomeSHOTS: String,
      HomeTeam: String,
    },
    awayTeamGoalieStats: [GoalieGameStatsSchema],
    homeTeamGoalieStats: [GoalieGameStatsSchema],
    awayTeamPlayerStats: [PlayerGameStatsSchema],
    homeTeamPlayerStats: [PlayerGameStatsSchema],
    gameHighlights: {
      type: [String],
      default: [],
    },
  },
  {
    timestamps: true,
  }
);

// const GameResult = models.GameResult || model("GameResult", GameResultSchema);

export default GameResultSchema;
